// ui/view/RelationshipEditView.tsx
import {RelationshipEdit} from "../edit/RelationshipEdit.tsx";
import {useAsync, useGraph} from "../utils/hooks";
import type {RelationshipEditViewData} from "./view.ts";

export function RelationshipEditView({data}: {
    data: RelationshipEditViewData,
}) {
    const graph = useGraph()

    const relationshipAsync = useAsync(async () => {
        return await graph.getRelationship(data.relationshipId)
    }, [graph, data])


    switch (relationshipAsync.status) {
        case "loading":
            return <>Loading</>
        case "error":
            return <>Error</>
        case "done":
            return <RelationshipEdit data={relationshipAsync.value!!}/>

    }
}

// packages/ui/src/view/RelationshipEditView.svelte
<script lang="ts">

    import {getGraph} from "../data/graph";
    import type {RelationshipEditViewData} from "./view";
    import RelationshipEdit from "../edit/RelationshipEdit.svelte";

    let graph = getGraph()

    export let data: RelationshipEditViewData

    let relationshipAsync = graph.getRelationship(data.relationshipId)

</script>

<div class="w-full flex justify-center">
    {#await relationshipAsync}
        Loading
    {:then relationship}
        <RelationshipEdit data={relationship}></RelationshipEdit>
    {/await}
</div>
