// packages/ui/src/cell/RelationshipCell.tsx
import {MoreOutlined} from "@ant-design/icons"
import {Button, Popover, Space} from "antd"
import {useContext} from "react"
import type {GraphRelationship} from "tabolo-core"
import {ViewHandlerContext} from "../view/view"

export function RelationshipCell({data}: {
    data: GraphRelationship
}) {
    const viewHandler = useContext(ViewHandlerContext)

    async function editRelationship() {
        await viewHandler.updateView({
            "type": "RelationshipEditView",
            "relationshipId": data.id,
        })
    }

    return <Popover title={`${data.type} Properties`} content={JSON.stringify(data.properties, null, 2)}>
        <Space.Compact block>
            <Button>{`<${data.type}>`}</Button>
            <Button icon={<MoreOutlined/>} onClick={editRelationship}/>
        </Space.Compact>
    </Popover>
}

// packages/ui/src/cell/RelationshipCell.svelte
<script lang="ts">
    import {Button, ButtonGroup, Popover} from "flowbite-svelte";
    import {idSelector, randomElementId} from "../util";
    import type {GraphRelationship} from "tabolo-core";
    import {DotsHorizontalOutline} from "flowbite-svelte-icons";
    import {getViewHandler} from "../view/view";

    export let data: GraphRelationship

    const viewHandler = getViewHandler()

    async function editRelationship() {
        await viewHandler.updateView({
            "type": "RelationshipEditView",
            "relationshipId": data.id,
        })
    }

    const id = randomElementId("relationship-cell")
</script>

<ButtonGroup size="sm">
    <Button {id}>{data.type}</Button>
    <Button on:click={editRelationship}>
        <DotsHorizontalOutline/>
    </Button>
</ButtonGroup>
<Popover title="Properties" triggeredBy={idSelector(id)}>
    {JSON.stringify(data.properties, null, 2)}
</Popover>
