// packages/ui/src/App.tsx
import {Layout} from "antd";
import {PrepareLocal} from "./json/PrepareLocal.tsx";
import {View} from "./view/View.tsx";

export function App() {
    return (
        <Layout>
            <Layout.Content>
                <PrepareLocal>
                    <View/>
                </PrepareLocal>
            </Layout.Content>
            <Layout.Footer>
                ©{new Date().getFullYear()}
                <a href="https://github.com/wang-x-xia/tabolo-app">Tabolo</a>
                All Rights Reserved.
            </Layout.Footer>
        </Layout>
    )
}

// packages/ui/src/App.svelte
<script lang="ts">
    import PrepareLocal from "./json/PrepareLocal.svelte";
    import {Footer, FooterCopyright} from "flowbite-svelte";
    import View from "./view/View.svelte";
</script>

<main class="min-h-screen max-h-screen overflow-auto">
    <PrepareLocal>
        <View/>
    </PrepareLocal>
    <Footer class="absolute bottom-0 left-0 z-10 w-full">
        <FooterCopyright by="Tabolo" href="https://github.com/wang-x-xia/tabolo-app"/>
    </Footer>
</main>
