// ui/view/NodeEditView.tsx
import {NodeEdit} from "../edit/NodeEdit.tsx";
import {useAsync, useGraph} from "../utils/hooks";
import type {NodeEditViewData} from "./view.ts";

export function NodeEditView({data}: {
    data: NodeEditViewData
}) {
    const graph = useGraph()
    const nodeAsync = useAsync(async () => {
        return graph.getNode(data.nodeId)
    }, [graph, data])

    switch (nodeAsync.status) {
        case "loading":
            return <>Loading</>
        case "error":
            return <>Error</>
        case "done":
            return <NodeEdit data={nodeAsync.value!!}/>

    }
}

// src/view/NodeEditView.svelte
<script lang="ts">

    import NodeEdit from "../edit/NodeEdit.svelte";
    import {getGraph} from "../data/graph";
    import type {NodeEditViewData} from "./view";

    let graph = getGraph()

    export let data: NodeEditViewData

    let nodeAsync = graph.getNode(data.nodeId)

</script>

{#await nodeAsync}
    Loading
{:then node}
    <NodeEdit data={node}></NodeEdit>
{/await}
