// packages/ui/src/edit/NodeEdit.svelte
<script lang="ts">
    import {type GraphNode, type GraphRelationship, relationshipNodeSearcher} from "tabolo-core";
    import {Button, ButtonGroup, Input, Label, Textarea} from "flowbite-svelte";
    import TypeSelect from "./TypeSelect.svelte";
    import {getGraphEdit} from "./graph-edit";
    import {getViewHandler} from "../view/view";
    import RelationshipCell from "../cell/RelationshipCell.svelte";
    import NodeIdCell from "../cell/NodeIdCell.svelte";
    import {getGraph} from "../data/graph";

    const graph = getGraph()
    const graphEdit = getGraphEdit()
    const viewHandler = getViewHandler()

    export let data: GraphNode

    let property: string

    async function reset() {
        property = JSON.stringify(data.properties)
    }

    reset()

    async function setType(type: string) {
        data = await graphEdit.editNodeType(data.id, type)
    }

    async function remove() {
        await graphEdit.removeNode(data.id)
        history.back()
    }

    async function copy() {
        let node = await graphEdit.copyNode(data.id);
        await viewHandler.updateView({
            "type": "NodeEditView",
            "nodeId": node.id
        });
    }

    async function save() {
        data = await graphEdit.editNodeProperty(data.id, JSON.parse(property))
    }

    let relationships: GraphRelationship[] = []

    async function setup() {
        relationships = await graph.searchRelationships(relationshipNodeSearcher(data.id))
    }

    async function createRelationship() {
        await graphEdit.newEmptyRelationship(data.id, data.id)
        await setup()
    }

    setup()
</script>

<div class="w-full max-w-3xl space-y-4">
    <Label class="mb-2 text-xl">Node ID</Label>
    <Input disabled value={data.id}/>
    <Label class="mb-2 text-xl">Action</Label>
    <ButtonGroup>
        <Button on:click={copy}>Copy</Button>
        <Button on:click={remove}>Delete</Button>
    </ButtonGroup>
    <Label class="mb-2 text-xl">Type</Label>
    <TypeSelect on:type={e =>setType(e.detail)} source="Node" type={data.type}/>
    <Label class="mb-2 text-xl">Property</Label>
    <Textarea bind:value={property} class="h-40"/>
    <ButtonGroup>
        <Button color="primary" on:click={save}>Save</Button>
        <Button color="alternative" on:click={reset}>Reset</Button>
    </ButtonGroup>
    {#if (relationships.length) === 0}
        <Label class="mb-2 text-xl">No Relationship</Label>
    {:else }
        <Label class="mb-2 text-xl">Relationships</Label>
        {#each relationships as relationship}
            <div>
                {#if (relationship.startNodeId !== data.id)}
                    <NodeIdCell data={relationship.startNodeId}/>
                {/if}
                <RelationshipCell data={relationship}/>
                {#if (relationship.endNodeId !== data.id)}
                    <NodeIdCell data={relationship.endNodeId}/>
                {/if}
            </div>
        {/each}
    {/if}
    <ButtonGroup>
        <Button on:click={createRelationship}>New Relationship</Button>
    </ButtonGroup>
</div>

// packages/ui/src/edit/NodeEdit.tsx
import {Button, Input, Space} from "antd";
import {useContext, useEffect, useState} from "react";
import {GraphNode, relationshipNodeSearcher} from "tabolo-core";
import {NodeIdCell} from "../cell/NodeCell.tsx";
import {RelationshipCell} from "../cell/RelationshipCell.tsx";
import {GraphContext} from "../data/graph";
import {useAsyncOrDefault} from "../utils/hooks.ts";
import {ViewHandlerContext} from "../view/view.ts";
import {GraphEditContext} from "./graph-edit.ts";
import {TypeSelect} from "./TypeSelect.tsx";

export function NodeEdit({data}: {
    data: GraphNode
}) {
    const graph = useContext(GraphContext)
    const graphEdit = useContext(GraphEditContext)
    const viewHandler = useContext(ViewHandlerContext)

    const [update, forceUpdate] = useState(0)
    const [local, setLocal] = useState(data)
    const [property, setProperty] = useState("")

    useEffect(() => {
        setProperty(JSON.stringify(data.properties))
        setLocal(data)
    }, [data])


    async function setType(type: string) {
        setLocal(await graphEdit.editNodeType(local.id, type))
    }

    async function remove() {
        await graphEdit.removeNode(local.id)
        history.back()
    }


    async function copy() {
        const node = await graphEdit.copyNode(data.id);
        await viewHandler.updateView({
            "type": "NodeEditView",
            "nodeId": node.id
        });
    }

    async function save() {
        setLocal(await graphEdit.editNodeProperty(data.id, JSON.parse(property)))
    }


    function reset() {
        setProperty(JSON.stringify(local.properties))
    }


    const relationships = useAsyncOrDefault([], async () => {
        return await graph.searchRelationships(relationshipNodeSearcher(data.id))
    }, [graph, local, update])


    async function createRelationship() {
        await graphEdit.newEmptyRelationship(data.id, data.id)
        forceUpdate(update + 1)
    }

    const relationshipsDom = relationships.length === 0 ?
        <div>No Relationship</div>
        : <>
            <div>Relationships</div>
            {
                relationships.map(relationship => {
                    const start = relationship.startNodeId === local.id ? <>Self</> :
                        <NodeIdCell data={relationship.startNodeId}/>
                    const end = relationship.endNodeId === local.id ? <>Self</> :
                        <NodeIdCell data={relationship.endNodeId}/>
                    return <>
                        {start}
                        <RelationshipCell data={relationship}/>
                        {end}
                    </>
                })
            }
        </>

    return <>
        <div>Node ID</div>
        <Input disabled value={local.id}/>
        <div>Action</div>
        <Space.Compact block>
            <Button onClick={copy}>Copy</Button>
            <Button onClick={remove}>Delete</Button>
        </Space.Compact>
        <div>Type</div>
        <TypeSelect type={local.type} source="Node" onChange={setType}/>
        <div>Property</div>
        <Input.TextArea rows={20} value={property} onChange={e => setProperty(e.target.value)}/>
        <Space.Compact block>
            <Button onClick={save}>Save</Button>
            <Button onClick={reset}>Reset</Button>
        </Space.Compact>
        {relationshipsDom}
        <Button onClick={createRelationship}>New Relationship</Button>
    </>
}
