// packages/ui/src/edit/RelationshipEdit.svelte
<script lang="ts">
    import type {GraphRelationship} from "tabolo-core";
    import {Button, ButtonGroup, Input, Label, Textarea} from "flowbite-svelte";
    import {getGraphEdit} from "./graph-edit";
    import {getViewHandler} from "../view/view";
    import TypeSelect from "./TypeSelect.svelte";
    import NodeSelect from "./NodeSelect.svelte";

    const graphEdit = getGraphEdit()
    const viewHandler = getViewHandler()

    export let data: GraphRelationship

    let property: string

    async function reset() {
        property = JSON.stringify(data.properties)
    }

    reset()

    async function setType(type: string) {
        data = await graphEdit.editRelationshipType(data.id, type)
    }

    async function remove() {
        await graphEdit.removeRelationship(data.id)
        history.back()
    }

    async function copy() {
        let relationship = await graphEdit.copyRelationship(data.id);
        await viewHandler.updateView({
            "type": "RelationshipEditView",
            "relationshipId": relationship.id
        });
    }

    async function save() {
        data = await graphEdit.editRelationshipProperty(data.id, JSON.parse(property))
    }

    async function updateNodeId(pos: "Start" | "End", nodeId: string) {
        if (pos === "Start") {
            data = await graphEdit.editRelationshipStartNode(data.id, nodeId)
        } else {
            data = await graphEdit.editRelationshipEndNode(data.id, nodeId)
        }
    }
</script>

<div class="w-full max-w-3xl space-y-4">
    <Label class="mb-2 text-xl">Relationship ID</Label>
    <Input disabled value={data.id}/>
    <Label class="mb-2 text-xl">Action</Label>
    <ButtonGroup>
        <Button on:click={copy}>Copy</Button>
        <Button on:click={remove}>Delete</Button>
    </ButtonGroup>
    <Label class="mb-2 text-xl">Type</Label>
    <TypeSelect on:type={e =>setType(e.detail)} source="Relationship" type={data.type}/>
    <Label class="mb-2 text-xl">Start Node</Label>
    <NodeSelect data={data.startNodeId} on:node={e => updateNodeId("Start", e.detail)}/>
    <Label class="mb-2 text-xl">End Node</Label>
    <NodeSelect data={data.endNodeId} on:node={e => updateNodeId("End", e.detail)}/>
    <Label class="mb-2 text-xl">Property</Label>
    <Textarea bind:value={property} class="h-40"/>
    <ButtonGroup>
        <Button color="primary" on:click={save}>Save</Button>
        <Button color="alternative" on:click={reset}>Reset</Button>
    </ButtonGroup>
</div>

// packages/ui/src/edit/RelationshipEdit.tsx
import {Button, Input, Space} from "antd";
import {useContext, useEffect, useState} from "react";
import {type GraphRelationship} from "tabolo-core";
import {NodeIdCell} from "../cell/NodeCell.tsx";
import {ViewHandlerContext} from "../view/view.ts";
import {GraphEditContext} from "./graph-edit.ts";
import {TypeSelect} from "./TypeSelect.tsx";

export function RelationshipEdit({data}: {
    data: GraphRelationship
}) {
    const graphEdit = useContext(GraphEditContext)
    const viewHandler = useContext(ViewHandlerContext)

    const [local, setLocal] = useState(data)
    const [property, setProperty] = useState("")

    useEffect(() => {
        setProperty(JSON.stringify(data.properties))
        setLocal(data)
    }, [data])


    async function setType(type: string) {
        setLocal(await graphEdit.editRelationshipType(local.id, type))
    }

    async function remove() {
        await graphEdit.removeRelationship(local.id)
        history.back()
    }


    async function copy() {
        const relationship = await graphEdit.copyRelationship(data.id);
        await viewHandler.updateView({
            "type": "RelationshipEditView",
            "relationshipId": relationship.id
        });
    }

    async function save() {
        setLocal(await graphEdit.editRelationshipProperty(data.id, JSON.parse(property)))
    }


    function reset() {
        setProperty(JSON.stringify(local.properties))
    }

    return <>
        <div>Relationship ID</div>
        <Input disabled value={local.id}/>
        <div>Action</div>
        <Space.Compact block>
            <Button onClick={copy}>Copy</Button>
            <Button onClick={remove}>Delete</Button>
        </Space.Compact>
        <div>Type</div>
        <TypeSelect type={local.type} source="Relationship" onChange={setType}/>
        <div>Start Node</div>
        <NodeIdCell data={data.startNodeId}/>
        <div>End Node</div>
        <NodeIdCell data={data.endNodeId}/>
        <div>Property</div>
        <Input.TextArea rows={20} value={property} onChange={e => setProperty(e.target.value)}/>
        <Space.Compact block>
            <Button onClick={save}>Save</Button>
            <Button onClick={reset}>Reset</Button>
        </Space.Compact>
    </>
}
